export interface DailyDeliverySummary {
  // Support both PascalCase (API) and camelCase (Angular convention)
  DeliveryId?: number;
  deliveryId?: number;
  DeliveryDate?: string;
  deliveryDate?: string;
  DriverName?: string;
  driverName?: string;
  VehicleId?: number;
  vehicleId?: number;
  VehicleNo?: string;
  vehicleNo?: string;
  VehicleNumber?: string;
  vehicleNumber?: string;
  StartTime?: string;
  startTime?: string;
  Status?: string;
  status?: string;
  ReturnTime?: string | null;
  returnTime?: string | null;
  Remarks?: string | null;
  remarks?: string | null;
  HasCreditCustomers?: boolean;
  hasCreditCustomers?: boolean;
  CompletedInvoices?: number;
  completedInvoices?: number;
  PendingInvoices?: number;
  pendingInvoices?: number;
  CashCollected?: number;
  cashCollected?: number;
  EmptyCylindersReturned?: number;
  emptyCylindersReturned?: number;
  OtherItemsDelivered?: number;
  otherItemsDelivered?: number;
  CylindersDelivered?: number;
  cylindersDelivered?: number;
  NonCylItemsDelivered?: number;
  nonCylItemsDelivered?: number;
  InvoiceCount?: number;
  invoiceCount?: number;
  DeliveryCount?: number;
  deliveryCount?: number;
  PlannedInvoices?: number;
  plannedInvoices?: number;
  TotalCollection?: number;
  totalCollection?: number;
  TotalItemsDelivered?: number;
  totalItemsDelivered?: number;
  DeliveryCompletionRate?: number;
  deliveryCompletionRate?: number;
}
